import type { SSOTRuleDefinition } from "./ssot-rule-registry.js";

/** 引擎内置 12 条 SSOT 边规则 —— port 自原 src/core/change-graph/edges.ts 的 EDGE_CATALOG
 *  matchRefField 是新增字段：让 Agent 写 .json 时用 data[matchRefField] = [targetId, ...]
 *  显式引用代替原来的位置匹配 */
export const BUILTIN_SSOT_RULES: SSOTRuleDefinition[] = [
  {
    id: "change-risk-to-req-nfr",
    fromPhases: ["change"],
    fromKind: "risk",
    toPhases: ["requirement"],
    toKind: "nfr",
    edgeKind: "derives_from",
    matchRefField: "mitigatedBy",
    violationEnabled: true,
    builtin: true,
  },
  {
    id: "req-nfr-to-design-threat",
    fromPhases: ["requirement"],
    fromKind: "nfr",
    toPhases: ["design"],
    toKind: "threat",
    edgeKind: "derives_from",
    matchRefField: "threats",
    violationEnabled: true,
    builtin: true,
  },
  {
    id: "design-threat-to-test-case",
    fromPhases: ["design"],
    fromKind: "threat",
    toPhases: ["test"],
    toKind: "test_case",
    edgeKind: "tests",
    matchRefField: "testedBy",
    builtin: true,
  },
  {
    id: "design-threat-to-review",
    fromPhases: ["design"],
    fromKind: "threat",
    toPhases: ["review"],
    toKind: "test_case",
    edgeKind: "tests",
    matchRefField: "reviewedBy",
    builtin: true,
  },
  {
    id: "req-ac-to-test-case",
    fromPhases: ["requirement"],
    fromKind: "acceptance_criterion",
    toPhases: ["test"],
    toKind: "test_case",
    edgeKind: "tests",
    matchRefField: "testedBy",
    builtin: true,
  },
  {
    id: "design-decision-to-task-slice",
    fromPhases: ["design"],
    fromKind: "design_decision",
    toPhases: ["task"],
    toKind: "slice",
    edgeKind: "implements",
    matchRefField: "implementedBy",
    matchStrategy: "exact",
    violationEnabled: true,
    builtin: true,
  },
  {
    id: "design-deploy-to-integration-monitor",
    fromPhases: ["design"],
    fromKind: "deployment_step",
    toPhases: ["integration"],
    toKind: "monitoring_metric",
    edgeKind: "monitors",
    matchRefField: "monitoredBy",
    builtin: true,
  },
  {
    id: "task-risk-to-design-risk",
    fromPhases: ["task"],
    fromKind: "risk",
    toPhases: ["design"],
    toKind: "risk",
    edgeKind: "derives_from",
    matchRefField: "derivedFrom",
    matchStrategy: "word-overlap-2",
    violationEnabled: true,
    builtin: true,
  },
  {
    id: "task-rollback-to-design-rollback",
    fromPhases: ["task"],
    fromKind: "rollback",
    toPhases: ["design"],
    toKind: "rollback",
    edgeKind: "rolls_back",
    matchRefField: "plannedIn",
    violationEnabled: true,
    builtin: true,
  },
  {
    id: "change-rollback-to-design-rollback",
    fromPhases: ["change"],
    fromKind: "rollback",
    toPhases: ["design"],
    toKind: "rollback",
    edgeKind: "duplicates",
    matchRefField: "designRef",
    violationEnabled: true,
    builtin: true,
  },
  {
    id: "design-rollback-to-integration",
    fromPhases: ["design"],
    fromKind: "rollback",
    toPhases: ["integration"],
    toKind: "rollback",
    edgeKind: "rolls_back",
    matchRefField: "executedIn",
    violationEnabled: true,
    builtin: true,
  },
  {
    id: "test-case-to-review",
    fromPhases: ["test"],
    fromKind: "test_case",
    toPhases: ["review"],
    toKind: "test_case",
    edgeKind: "tests",
    matchRefField: "reviewedBy",
    builtin: true,
  },
];
